DELETE FROM CONN_SERVICES_PROP WHERE SERVICE_ID IN (SELECT SERVICE_ID FROM CONN_SERVICES WHERE ENDPOINT_ID='CmssHttpSoap');
DELETE FROM CONN_SERVICES WHERE ENDPOINT_ID = 'CmssHttpSoap';
DELETE FROM CONN_ENDPOINT_PROP WHERE ENDPOINT_ID = 'CmssHttpSoap';
DELETE FROM CONN_ENDPOINT WHERE ENDPOINT_ID = 'CmssHttpSoap';

INSERT INTO CONN_ENDPOINT (ENDPOINT_ID,SCHEME,HOSTNAME,PORT,PATH,DESCRIPTION) VALUES ('CmssHttpSoap','https','',443,'','CMSS ESB endpoint');
INSERT INTO CONN_ENDPOINT_PROP (ENDPOINT_ID,NAME,VALUE,DESCRIPTION) VALUES ('CmssHttpSoap','HardErrorCode','080000','Default error code for backend CMSS ESB');


INSERT INTO CONN_SERVICES(SERVICE_ID, ENDPOINT_ID,AUTH_ID,BACKEND,MT,MV,NAMESPACE) VALUES (, 'CmssHttpSoap', CmssHttpSoapAuth, 'CMSESB','GetClientZoneSSOUrlRequest', 1, 'http://service.cmss.cz/security/SSOSecurityService/v01');		INSERT INTO CONN_SERVICES_PROP(SERVICE_ID,NAME,VALUE,DESCRIPTION) VALUES (,'Path','','Service Path - CMSS ESB - getClientZoneSSOUrl');
